services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: inception-mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: inception-wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: inception-nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nbenhssi/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nbenhssi/data/wordpress

networks:
  inception: